### ISSUE TITLE
when turns on 'zoom active card' ,..

### ISSUE THREAD

**Issue by hemmy** [rpetrich/ProSwitcher#165]
the closing button seems too slow move back to corner..

**Comment by heresjohnny** [comment]
Agreed. It does a weird falling from the top animation. Is this what's supposed to happen? If so, can there be an option to remove it? 

Also can there be an option to let the Springboard page have the total number of badges in the corner? Sorry if that made no/little sense.

**Comment by GabsNL** [comment]
Yes @OP I think this is a bug.

**Comment by grp** [comment]
Please keep this to one bug/request per issue. Second bugs will not be considered.

Anyway, I need a screenshot/video.

**Comment by heresjohnny** [comment]
I can't make a video of it, but hopefully someone else can. It might be reproducible if you use the following settings: Card Visible = 3, Zoom Active Card = On, Close Button = On. I think it's the Zoom Active Card setting that's causing the close button to "fall" from the top, because when it's off, the close button fades in perfectly.

**Comment by GabsNL** [comment]
heresjohnny is right Zoom Active Card seems to cause this little glitch.

Ps: @heresjohnny: I loved The Shining :)
