### ISSUE TITLE
Hide Default Apps Toggle is gone in 1.0 now!

### ISSUE THREAD

**Issue by atoxx** [rpetrich/ProSwitcher#179]
Hi today i resetted mmy iphone or better i restored it to factory settings and started over but now on ProSwitcher the Hide Default Apps Toggle is not there anymore, any reason why this is?

Tried the top actual Version but no luck, tried also an older one, it was 0.7 or similar but even then, it was not there ....
Anyone a suggestion how to solver this?

**Comment by sysrage** [comment]
Yes. This is gone. I don't understand why all of these very useful settings are being hidden. Why do you want users editing plists for basic features?

**Comment by atoxx** [comment]
Yes this was one of the Points of Interests to hide Mail, Phone and iPod App which are always backgrounded and i had no problems with this during the last days and i do not understand why they were removed, so if ppl have problems with this thay can turn it off but now my Active Apps List is messed up with the default Apps, this sucks...

**Comment by atoxx** [comment]
Now that ProSwitchr is finall i gave up the Hope this will be incuded soon, so anyone knows which Value is to be added to the Plist to activate this?

Thx in advance

**Comment by GabsNL** [comment]
rPetrich told me this a while ago, maybe you should try it: 

A PSWDefaultApps key needs to be set in com.collab.proswitcher.plist; it should be set to an array of displayIdentifiers of applications to be considered "default"

**Comment by sysrage** [comment]
Major mistake to start asking users to modify the plist for all these hidden settings. I understand for some of them that you would only want advanced users messing with, but there is no reason to hide simple (and somewhat common) settings from users such as this and the status bar swipe activation methods. You're just asking for wasted time with support issues. I can edit the plist myself, but you know as well as I do that many users will break something while manually editing it then come here complaining and asking for support. Not only that but youll have people bad mouthing the app due to missing features that you already coded, but for some reason decided to hide. That said, it's your app. Do what you need to. Probably worth considering, though.

**Comment by grp** [comment]
This is a bug, yes, I accidentally deleted it. I can't do any more devel or coding until saturday but I will try then.

**Comment by rpetrich** [comment]
Fixed this in unstable

**Comment by rpetrich** [comment]
sysrage: Would it be better if ProSwitcher didn't read hidden settings from disk? Advanced users would have to compile their own versions of ProSwitcher just to use them at all.

**Comment by sysrage** [comment]
No, I didn't say that. In fact, I specifically said I understood the reasoning for some settings being hidden. I wasn't being difficult. I told you to do what you needed to do. I was simply making a point that some of these very basic settings, that many many users will probably want, now appeared to be hidden. I didn't know this one was a bug and I didn't know the status bar swipe activation methods were requested to be removed by BigBoss and would return soon. I opened the bug and was simply told that it wasn't a bug. I understand how hard you guys are working. I appreciate it. Simply giving my opinion.

**Comment by rpetrich** [comment]
<sup>(my last post should be taken tongue in cheek; I was merely trying to point out that we need different levels of visibility based on how advanced/completed a capability is)</sup>
