### ISSUE TITLE
Zoom is transparent

### ISSUE THREAD

**Issue by verzel** [rpetrich/ProSwitcher#183]
As it is now, apps that zoom in and out from PS become transparent for part of the zooming transition.  It would be way more realistic if the transparency could be eliminated, providing that the zooming proportions are correct.

**Comment by GabsNL** [comment]
I would love for this to be fixed.
The zoom is kinda like Orbit's zoom now.
A good example of perfect zoom is OverBoard's. :)

**Comment by grp** [comment]
Not a bug.

**Comment by rpetrich** [comment]
GabsNL: Oddly enough, ProSwitcher uses the exact same zoom as OverBoard :P

**Comment by Sonola777** [comment]
Seriously though, the animation transitions still need work. This is the one area where Multifl0w has a leg up on you guys. Compared to the animations in Mobile Safari, ProSwitcher has a long way to go. You guys are damn good at what you do, I know you can match those apps.

**Comment by GabsNL** [comment]
I don't want to be whining and ProSwitcher is already looking really great, I do have to agree with Sonola777. I tried capturing what I meant with the zoom and managed to get two good screens of it.

Ones again, you guys are doing a phenomenal job with this! Just wanted to point things out that could improve it in the future. :)

Zoom out: http://img22.imageshack.us/img22/9103/img0280.png
Zoom in: http://img526.imageshack.us/img526/1158/img0292.png
I would be great to have opening ProSwitcher zoom WITH or be part of the animations, Instead of already being there when the animations occur. A good example of this is indeed MobileSafari.

Ones again, you guys are doing a phenomenal job on this. Just wanted to point some stuff out that can improve it in the future. :)

**Comment by rpetrich** [comment]
MobileSafari goes through the whole "fake zoom content" routine that we do, but because it controls the entire process, a flip from real content to screenshot can be made. We don't have that luxury and use a fade to cover up the corner cases where it doesn't look proper. If we ever do cover those cases, we may remove the fade from the zoom animation.

**Comment by GabsNL** [comment]
Thank you for explaining, Ryan.
