### ISSUE TITLE
Sorry to insist... Pop up at respring

### ISSUE THREAD

**Issue by anonimous** [rpetrich/ProSwitcher#369]
Yes, I'm one more fed up with the pop up reminding us that ProSwitcher HD is still an Alpha. I understand your effords, congratulate you for the application and thank you for giving it us for free. That said, I would like to get ride of the pop up. I'll report any bug I find, I promise.
People jailbreak their devices:
a.- To Install apps without payinf for them
b.- To get the most of them (homebrew, new apps, more control over it,...)
The ones that have searched for a solution to the annoying pop up and found this forum are probably type b, and we install-reinstall apps/respring/reboot quite often so PLEASE, tell us a way to disable it (I've already read all the post and if I keep on deleting things in proswitcher.dylib I'll have to restore my iPad)
To any user who knows how to do it, PLEASE, send me a mail.
Thank you

**Comment by grp** [comment]
This is an Alpha release. The popup is to remind you that you shouldn't be using this on a device except for testing and debugging. If you are, that is a misuse of an alpha release and it shouldn't be used that way, you should wait for the final release.

Therefore, you should uninstall ProSwitcher when not debugging it. This popup is merely a reminder about that, and should not be an issue, since it is only installed when debugging.

Issue closed.

**Comment by anonimous** [comment]
In fact, everytime I install something is for testing because lot of the apps have bugs (even Activator had problems with the Volume icon in version 1.4.4, I think) I would like to be alble to debug apps, but I'm just a final user (no idea at all about programing) I have it installed because it's much better than Multiflow or any other multitasking app.
I hope you'll release the final version soon (althought, in the best, there'll probably be a beta1, beta2, beta3 version with the pop up...)
