### ISSUE TITLE
Status Bar Scrolling

### ISSUE THREAD

**Issue by verzel** [rpetrich/ProSwitcher#57]
When you do anything with the status bar as a trigger for proswitcher, it scrolls whatever you're looking at back to the top, per the normal iphone action of a single tap to the status bar.  in some cases, this defeats the entire purpose of multitasking.

**Comment by dharris** [comment]
I can confirm this.

**Comment by grp** [comment]
Please post on the libactivator bug section; this is _not_ in ProSwitcher.

**Comment by rpetrich** [comment]
Since a libactivator bug hasn't been filed:

The scroll-to-top action occurs on touchesBegan not during touchesMoved or touchesEnded; that means that before libactivator even begins listening for a gesture, the active scroll view is already moving to the top. I can't see a way around this that isn't intrusive.
