### ISSUE TITLE
Lag on Public Beta (0.7.3)

### ISSUE THREAD

**Issue by macfan406** [rpetrich/ProSwitcher#88]
The application has a large amount of lag.

**Comment by grp** [comment]
What the hell is that supposed to mean?

**Comment by GabsNL** [comment]
Try deactivating Rounded corners if you have that set as small or large.
Also more info would be helpful for the devs. :p

**Comment by grp** [comment]
Yeah :)

**Comment by macfan406** [comment]
It just doesn't seem as fast as other versions and does rounded corners just make it look more like a Pre?

**Comment by macfan406** [comment]
Yeah.. it does
I'll disable it til i get a 3GS that i can at least semi-tether jailbreak

**Comment by GabsNL** [comment]
Rounded corners does indeed make it more look like Pre but causes serious lag on the older devices (not much the devs can do about this).
I did also notice that ProSwitcher 0.7.3 was a tad bit slower then previous iterations, which is weird because rPetrich noted that this version had some performance improvements :p
Hopefully The speed gets back on par in the next release.

**Comment by rpetrich** [comment]
Placebo effect. The performance sensitive areas weren't changed at all in 0.7.3 (one such change was made in 0.7.2, but I didn't tweet that release and I lumped its changes into the 0.7.3 tweet)

Also, closing this issue; there's nothing to fix here.
